# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20180911_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('data', models.CharField(blank=True, max_length=100000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=10, max_length=10, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Membership')),
            ],
        ),
    ]
