# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20180911_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='publish_date',
            new_name='diggest_date',
        ),
    ]
