# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20180911_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'circle')]),
        ),
    ]
