# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20180911_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
