# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-11 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_issue_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('user', 'issue')]),
        ),
    ]
