# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-16 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20180911_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='data_html',
        ),
    ]
